import { useRef, useState } from "react";
import { useNavigate } from "react-router-dom";
import {
  CalendarRange,
  Clock3,
  Copy,
  Download,
  FileText,
  Mail,
  Share2,
  Sparkles,
  Upload,
  LayoutList,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Label } from "@/components/ui/label";
import { Avatar } from "@/components/ui/avatar";
import { useToast } from "@/lib/toast";
import { historyStore, ActionItem } from "@/lib/historyStore";

const ownerPool = ["Anna", "Victor", "Priya", "Samir", "Jordan"];

const defaultTranscript = `Team sync focused on the March launch. Design delivered final homepage sections. Marketing needs the launch plan locked by Feb 29 for ads. Engineering flagged risk on analytics events stability. Decision: push mobile release to April to protect web quality. Announcements will go to beta users next Tuesday. Product wants weekly Tuesday standups moving forward.`;

// Renders **bold** as cyan highlight + auto-highlights time/priority keywords
function HighlightText({ text }: { text: string }) {
  const timeWords = /\b(tonight|today|tomorrow|monday|tuesday|wednesday|thursday|friday|saturday|sunday|urgent|asap)\b/gi;
  const priorityWords = /\b(high|critical|important)\b/gi;

  // Split on **...** bold markers first
  const parts = text.split(/(\*\*[^*]+\*\*)/g);
  return (
    <>
      {parts.map((part, i) => {
        if (part.startsWith("**") && part.endsWith("**")) {
          return (
            <span key={i} className="font-semibold text-cyan-300">
              {part.slice(2, -2)}
            </span>
          );
        }
        // Auto-highlight time/deadline words in amber
        const subParts = part.split(/(\b(?:tonight|today|tomorrow|monday|tuesday|wednesday|thursday|friday|saturday|sunday|urgent|asap|high|critical|important)\b)/gi);
        return subParts.map((sub, j) => {
          if (timeWords.test(sub)) return <span key={`${i}-${j}`} className="font-medium text-amber-300">{sub}</span>;
          if (priorityWords.test(sub)) return <span key={`${i}-${j}`} className="font-medium text-rose-400">{sub}</span>;
          return <span key={`${i}-${j}`}>{sub}</span>;
        });
      })}
    </>
  );
}

// interface ActionItem removed - imported from historyStore

function buildMarkdown(transcript: string, summary: string, keyPoints: string[], actionItems: ActionItem[]) {
  const rows = actionItems.map(
    (i) => `| ${i.task} | ${i.owner} | ${i.deadline} | ${i.priority} | `
  );
  return [
    "# Meeting Summary – MeetMind AI",
    "",
    "## Summary",
    summary,
    "",
    "## Key Points",
    ...keyPoints.map((p) => `- ${p} `),
    "",
    "## Action Items",
    "| Task | Owner | Deadline | Priority |",
    "|------|-------|----------|----------|",
    ...rows,
    "",
    "---",
    "*Generated by MeetMind AI*",
  ].join("\n");
}

export function DashboardPage() {
  const [transcript, setTranscript] = useState("");
  const [loading, setLoading] = useState(false);
  const [generated, setGenerated] = useState(false);
  const [summary, setSummary] = useState("");
  const [keyPoints, setKeyPoints] = useState<string[]>([]);
  const [actionItems, setActionItems] = useState<ActionItem[]>([]);
  const [owners, setOwners] = useState<string[]>([]);

  const fileInputRef = useRef<HTMLInputElement>(null);
  const toast = useToast();
  const navigate = useNavigate();

  const handleGenerate = async () => {
    if (!transcript.trim()) {
      toast("Please enter a transcript first.", "warning");
      return;
    }

    setLoading(true);
    try {
      const response = await fetch("http://localhost:8000/api/v1/summarize", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ transcript }),
      });

      if (!response.ok) {
        throw new Error(`Error ${response.status}: ${response.statusText}`);
      }

      const result = await response.json();

      setSummary(result.summary);
      setKeyPoints(result.key_points ?? result.key_points_discussed ?? []);
      setActionItems(result.action_items);

      // Update owners list from action items
      const newOwners = Array.from(new Set(result.action_items.map((i: ActionItem) => i.owner).filter((o: string) => o !== "Unassigned"))) as string[];
      setOwners(newOwners.length > 0 ? newOwners : ["Anna", "Victor", "Priya"]);

      setGenerated(true);

      // Save to history
      historyStore.saveMeeting({
        title: `Meeting on ${new Date().toLocaleDateString()}`,
        date: new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }),
        owner: newOwners[0] || "Multiple",
        actions: result.action_items,
        tags: ["AI Generated"],
        keyPoints: result.key_points ?? result.key_points_discussed ?? [],
        summary: result.summary,
        transcriptSample: transcript.slice(0, 100) + "..."
      });

      toast("Summary generated and saved to History!");
    } catch (error) {
      console.error("API Error:", error);
      toast("Failed to connect to AI backend. Ensure the server is running on port 8000.", "error");
    } finally {
      setLoading(false);
    }
  };

  const handleShareRecap = async () => {
    const text = `Meeting Recap – MeetMind AI\n\n${summary} \n\nAction items: ${actionItems.map((i) => `${i.task} (${i.owner}, ${i.deadline})`).join(" | ")} `;
    await navigator.clipboard.writeText(text);
    toast("Recap copied to clipboard – paste anywhere!");
  };

  const handleUploadClick = () => {
    fileInputRef.current?.click();
  };

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    if (file.type === "text/plain" || file.name.endsWith(".txt")) {
      const reader = new FileReader();
      reader.onload = (ev) => {
        setTranscript(ev.target?.result as string);
        toast(`"${file.name}" loaded into transcript.`);
      };
      reader.readAsText(file);
    } else {
      setTranscript(`[Transcript from: ${file.name}]\n\nPDF text extraction requires backend integration.Please paste the transcript text directly.`);
      toast("PDF detected – paste transcript text for full AI analysis.", "warning");
    }
    // Reset so same file can be re-selected
    e.target.value = "";
  };

  const handleCopyMarkdown = async () => {
    const md = buildMarkdown(transcript, summary, keyPoints, actionItems);
    await navigator.clipboard.writeText(md);
    toast("Markdown copied to clipboard ✓");
  };

  const handleDownloadPDF = () => {
    const content = buildMarkdown(transcript, summary, keyPoints, actionItems);
    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "meeting-summary.md";
    a.click();
    URL.revokeObjectURL(url);
    toast("meeting-summary.md downloaded!");
  };

  const handleExportCSV = () => {
    if (actionItems.length === 0) {
      toast("No action items to export.", "warning");
      return;
    }
    const csvContent = historyStore.generateCSV(actionItems);
    const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.setAttribute("href", url);
    link.setAttribute("download", "action_items.csv");
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    toast("Action items exported to CSV!");
  };

  const handleCopyMarkdownActions = async () => {
    // Just the action items table
    const rows = actionItems.map(
      (i) => `| ${i.task} | ${i.owner} | ${i.deadline} | ${i.priority} | `
    );
    const table = [
      "| Task | Owner | Deadline | Priority |",
      "|------|-------|----------|----------|",
      ...rows,
    ].join("\n");
    await navigator.clipboard.writeText(table);
    toast("Action items table copied to Markdown!");
  };

  const handleExportTrello = async () => {
    if (actionItems.length === 0) {
      toast("No action items to export.", "warning");
      return;
    }

    const key = localStorage.getItem("trello_key");
    const token = localStorage.getItem("trello_token");
    const listId = localStorage.getItem("trello_list_id");

    if (key && token && listId) {
      toast("Exporting to Trello (using custom keys)...", "info");
      try {
        const res = await fetch("http://localhost:8000/api/v1/export/trello", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            api_key: key,
            token: token,
            list_id: listId,
            action_items: actionItems
          })
        });
        if (!res.ok) throw new Error("API Export Failed");
        const data = await res.json();
        toast(`Successfully created ${data.cards_created} cards in Trello!`, "success");
        return;
      } catch (e) {
        console.error(e);
        toast("Custom Trello export failed. Trying server defaults...", "error");
      }
    }

    // Try server-side default keys
    toast("Exporting to Trello (using server defaults)...", "info");
    try {
      const res = await fetch("http://localhost:8000/export-to-trello", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          action_items: actionItems
        })
      });

      if (res.ok) {
        const data = await res.json();
        if (data.success) {
          toast(`Successfully created ${data.created_card_ids.length} cards in Trello!`, "success");
          return;
        }
      }
    } catch (e) {
      console.log("Server default export failed", e);
    }

    // Fallback if both fail
    const trelloText = actionItems.map(item =>
      `${item.task}\nDescription: Owner: ${item.owner} | Deadline: ${item.deadline} | Priority: ${item.priority}\n`
    ).join("\n---\n\n");

    await navigator.clipboard.writeText(trelloText);
    toast("Export failed. Copied to clipboard instead.", "warning");
  };

  const handleExportNotion = async () => {
    if (actionItems.length === 0) {
      toast("No action items to export.", "warning");
      return;
    }

    const token = localStorage.getItem("notion_token");
    const pageId = localStorage.getItem("notion_page_id");

    if (token && pageId) {
      toast("Exporting to Notion...", "info");
      try {
        const res = await fetch("http://localhost:8000/api/v1/export/notion", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            token: token,
            parent_page_id: pageId,
            title: `Meeting Summary - ${new Date().toLocaleDateString()}`,
            summary: summary,
            action_items: actionItems
          })
        });
        if (!res.ok) throw new Error("API Export Failed");
        toast("Successfully exported to Notion page!", "success");
        return;
      } catch (e) {
        console.error(e);
        toast("Notion API export failed. Falling back to clipboard.", "error");
      }
    }

    // Notion friendly format: Markdown checkbox list
    const notionText = actionItems.map(item =>
      `- [ ] **${item.task}**\n  - Owner: ${item.owner}\n  - Deadline: ${item.deadline}\n  - Priority: ${item.priority}`
    ).join("\n");

    await navigator.clipboard.writeText(notionText);
    toast("Copied to clipboard! (Configure keys in Settings for direct export)");
  };

  const handleAutoAssign = () => {
    setActionItems((prev) =>
      prev.map((item, i) => ({
        ...item,
        owner: ownerPool[i % ownerPool.length],
      }))
    );
    toast("Owners auto-assigned from your team roster.");
  };

  return (
    <div className="space-y-6">
      {/* Hidden file input */}
      <input
        ref={fileInputRef}
        type="file"
        accept=".txt,.pdf"
        className="hidden"
        onChange={handleFileChange}
      />

      <div className="flex flex-wrap items-center justify-between gap-3">
        <div>
          <p className="text-sm text-slate-400">AI Meeting Notes &amp; Actions</p>
          <h1 className="text-2xl font-semibold">Dashboard</h1>
        </div>
        <div className="flex items-center gap-2">
          <Button variant="secondary" size="sm" onClick={handleShareRecap}>
            <Mail className="h-4 w-4" /> Share recap
          </Button>
          <Button variant="primary" size="sm" onClick={handleGenerate} disabled={loading}>
            <Sparkles className="h-4 w-4" />
            {loading ? "Generating..." : "Generate summary"}
          </Button>
        </div>
      </div>

      <div className="grid gap-6 lg:grid-cols-[1.1fr_0.9fr]">
        <Card className="border-white/5 bg-white/5 p-5">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm text-slate-300">Settings &amp; API Keys</p>
              <p className="text-xs text-slate-400">Configure integrations for direct export</p>
            </div>
          </div>
          <div className="mt-4 space-y-4">
            <div className="space-y-2">
              <Label>Notion Integration</Label>
              <div className="grid gap-2 sm:grid-cols-2">
                <input
                  type="password"
                  placeholder="Notion Integration Token"
                  className="rounded-md border border-white/10 bg-black/20 px-3 py-2 text-sm text-slate-200 placeholder:text-slate-500 focus:border-cyan-500/50 focus:outline-none"
                  onChange={(e) => localStorage.setItem("notion_token", e.target.value)}
                  defaultValue={localStorage.getItem("notion_token") || ""}
                />
                <input
                  type="text"
                  placeholder="Parent Page ID"
                  className="rounded-md border border-white/10 bg-black/20 px-3 py-2 text-sm text-slate-200 placeholder:text-slate-500 focus:border-cyan-500/50 focus:outline-none"
                  onChange={(e) => localStorage.setItem("notion_page_id", e.target.value)}
                  defaultValue={localStorage.getItem("notion_page_id") || ""}
                />
              </div>
            </div>

            <div className="space-y-2">
              <Label>Trello Integration</Label>
              <div className="grid gap-2 sm:grid-cols-3">
                <input
                  type="password"
                  placeholder="API Key"
                  className="rounded-md border border-white/10 bg-black/20 px-3 py-2 text-sm text-slate-200 placeholder:text-slate-500 focus:border-cyan-500/50 focus:outline-none"
                  onChange={(e) => localStorage.setItem("trello_key", e.target.value)}
                  defaultValue={localStorage.getItem("trello_key") || ""}
                />
                <input
                  type="password"
                  placeholder="Token"
                  className="rounded-md border border-white/10 bg-black/20 px-3 py-2 text-sm text-slate-200 placeholder:text-slate-500 focus:border-cyan-500/50 focus:outline-none"
                  onChange={(e) => localStorage.setItem("trello_token", e.target.value)}
                  defaultValue={localStorage.getItem("trello_token") || ""}
                />
                <input
                  type="text"
                  placeholder="List ID"
                  className="rounded-md border border-white/10 bg-black/20 px-3 py-2 text-sm text-slate-200 placeholder:text-slate-500 focus:border-cyan-500/50 focus:outline-none"
                  onChange={(e) => localStorage.setItem("trello_list_id", e.target.value)}
                  defaultValue={localStorage.getItem("trello_list_id") || ""}
                />
              </div>
            </div>
          </div>
        </Card>

        <Card className="border-white/5 bg-white/5 p-5">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm text-slate-300">Transcript input</p>
              <p className="text-xs text-slate-400">Paste notes or upload a file (.txt / .pdf)</p>
            </div>
            <div className="flex items-center gap-2">
              <Button variant="ghost" size="sm" className="border border-white/10" onClick={handleUploadClick}>
                <Upload className="h-4 w-4" /> Upload file
              </Button>
            </div>
          </div>
          <div className="mt-4 space-y-3">
            <Label>Raw transcript</Label>
            <Textarea
              rows={8}
              value={transcript}
              onChange={(e) => setTranscript(e.target.value)}
              placeholder={`// Paste your meeting transcript here...
// Example: ${defaultTranscript.slice(0, 120)}...`}
            />
            <div className="grid gap-3 sm:grid-cols-2">
              <div className="flex items-center gap-2 text-xs text-slate-300">
                <CalendarRange className="h-4 w-4 text-cyan-300" /> Demo meeting on Feb 19
              </div>
              <div className="flex items-center gap-2 text-xs text-slate-300">
                <Clock3 className="h-4 w-4 text-cyan-300" /> Runtime: ~15 seconds per summary
              </div>
            </div>
          </div>
        </Card>

        <Card className="border-white/5 bg-white/5 p-5">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm text-slate-300">Export &amp; share</p>
              <p className="text-xs text-slate-400">Trigger exports after summary generation</p>
            </div>
          </div>
          <div className="mt-4 grid gap-3 sm:grid-cols-2">
            <Button variant="secondary" className="justify-center" onClick={handleCopyMarkdown}>
              <Copy className="h-4 w-4" /> Copy Full Markdown
            </Button>
            <Button variant="secondary" className="justify-center" onClick={handleDownloadPDF}>
              <Download className="h-4 w-4" /> Download .md
            </Button>
            <Button variant="ghost" className="justify-center border border-white/10 text-slate-200" onClick={handleExportCSV}>
              <FileText className="h-4 w-4" /> Export Actions (CSV)
            </Button>
            <Button variant="ghost" className="justify-center border border-white/10 text-slate-200" onClick={handleCopyMarkdownActions}>
              <Share2 className="h-4 w-4" /> Copy Actions (MD)
            </Button>
            <Button variant="ghost" className="justify-center border border-white/10 text-slate-200 hover:bg-blue-900/20 hover:text-blue-200" onClick={handleExportTrello}>
              <LayoutList className="mr-2 h-4 w-4" /> Export to Trello
            </Button>
            <Button variant="ghost" className="justify-center border border-white/10 text-slate-200 hover:bg-slate-100/10" onClick={handleExportNotion}>
              <FileText className="mr-2 h-4 w-4" /> Export to Notion
            </Button>
          </div>
          <div className="mt-4 rounded-lg border border-white/10 bg-white/5 p-3 text-xs text-slate-300">
            Export action items to Jira, Asana, or Linear via CSV, or copy Markdown for Notion.
          </div>
        </Card>
      </div>

      <div className="grid gap-6 xl:grid-cols-[1.1fr_0.9fr]">
        <Card className="border-white/5 bg-white/5 p-5">
          <div className="flex items-center justify-between">
            <h2 className="text-lg font-semibold">AI Summary</h2>
            <Badge tone={generated ? "success" : undefined} className={generated ? "" : "bg-white/10 text-white"}>
              {generated ? "Live output" : "Demo output"}
            </Badge>
          </div>
          {summary ? (
            <p className="mt-3 text-sm text-slate-200 leading-relaxed">
              <HighlightText text={summary} />
            </p>
          ) : (
            <p className="mt-3 text-sm text-slate-500 italic">No summary yet — paste a transcript and click Generate summary.</p>
          )}
          {owners.length > 0 && (
            <div className="mt-4">
              <p className="text-xs uppercase tracking-[0.2em] text-cyan-200">Owners</p>
              <div className="mt-2 flex gap-3">
                {owners.map(name => <Avatar key={name} name={name} />)}
              </div>
            </div>
          )}
        </Card>

        <Card className="border-white/5 bg-white/5 p-5">
          <div className="flex items-center justify-between">
            <h2 className="text-lg font-semibold">Key points</h2>
            <Badge className="bg-white/10 text-white">Claude API placeholder</Badge>
          </div>
          <ul className="mt-4 space-y-3 text-sm text-slate-200">
            {keyPoints.length > 0 ? keyPoints.map((point) => (
              <li key={point} className="flex items-start gap-2">
                <Sparkles className="mt-0.5 h-4 w-4 shrink-0 text-cyan-300" />
                <span><HighlightText text={point} /></span>
              </li>
            )) : (
              <li className="text-slate-500 italic">Key points will appear here after generation.</li>
            )}
          </ul>
        </Card>
      </div>

      <Card className="border-white/5 bg-white/5 p-5">
        <div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
          <div>
            <h2 className="text-lg font-semibold">Action items</h2>
            <p className="text-sm text-slate-400">Owners, deadlines, and priority tags extracted from transcript</p>
          </div>
          <Button variant="secondary" size="sm" onClick={handleAutoAssign}>
            <Sparkles className="h-4 w-4" /> Auto-assign owners
          </Button>
        </div>
        <div className="mt-4 overflow-x-auto">
          {actionItems.length > 0 ? (
            <table className="min-w-full text-left text-sm text-slate-100">
              <thead>
                <tr className="border-b border-white/10 text-slate-300">
                  <th className="py-2 pr-4">Task</th>
                  <th className="py-2 pr-4">Owner</th>
                  <th className="py-2 pr-4">Deadline</th>
                  <th className="py-2">Priority</th>
                </tr>
              </thead>
              <tbody>
                {actionItems.map((item) => (
                  <tr key={item.task} className="border-b border-white/5">
                    <td className="py-3 pr-4 align-top text-slate-100">
                      <HighlightText text={item.task} />
                    </td>
                    <td className="py-3 pr-4 align-top"><Badge className="bg-white/10 text-white">{item.owner}</Badge></td>
                    <td className="py-3 pr-4 align-top font-medium text-amber-300">{item.deadline}</td>
                    <td className="py-3 align-top">
                      <Badge tone={item.priority === "High" ? "danger" : item.priority === "Medium" ? "warning" : "default"}>
                        {item.priority}
                      </Badge>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          ) : (
            <p className="py-6 text-center text-sm text-slate-500 italic">Action items will appear here after generation.</p>
          )}
        </div>
      </Card>
    </div>
  );
}
