import { Link } from "react-router-dom";
import {
  ArrowRight,
  CheckCircle2,
  Clock3,
  Files,
  ShieldCheck,
  Sparkles,
  Users,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { useToast } from "@/lib/toast";

const featureBlocks = [
  {
    title: "Paste or upload transcripts",
    description: "Handle raw meeting notes, recordings, or text dumps. PDFs and .txt supported.",
    icon: <Files className="h-5 w-5" />,
  },
  {
    title: "AI summary + key points",
    description: "Claude-powered summaries with talking points, decisions, and risks.",
    icon: <Sparkles className="h-5 w-5" />,
  },
  {
    title: "Action items with owners",
    description: "Auto-extract tasks, deadlines, owners, and priority tags for accountability.",
    icon: <CheckCircle2 className="h-5 w-5" />,
  },
  {
    title: "Export anywhere",
    description: "Copy as Markdown, PDF, Trello cards, or push to Notion pages in a click.",
    icon: <ArrowRight className="h-5 w-5" />,
  },
];

const pricing = [
  {
    name: "Team",
    price: "$29",
    note: "/user/mo",
    features: ["Unlimited summaries", "Shared meeting history", "Task export to Trello/Notion"],
    cta: "Start free trial",
  },
  {
    name: "Pro",
    price: "$15",
    note: "/user/mo",
    features: ["3 meetings/day", "Email & Slack exports", "AI action items"],
    cta: "Go Pro",
  },
];

const sampleMarkdown = `# Meeting Summary – MeetMind AI

## Summary
Website revamp launch set for Mar 14. Marketing owns launch plan. Engineering to
finalize API stability by Mar 7. Weekly standups move to Tuesdays.

## Action Items
- Anna to ship homepage copy by Mar 1 (High)
- Vic to confirm analytics plan with Data by Feb 27 (Medium)
- Priya to update onboarding deck for sales by Mar 5 (High)

---
*Generated by MeetMind AI*`;

export function LandingPage() {
  const toast = useToast();

  const handleCopyMarkdown = async () => {
    await navigator.clipboard.writeText(sampleMarkdown);
    toast("Sample markdown copied to clipboard!");
  };

  const handleExportTrello = () => {
    toast("Open the dashboard and connect Trello in Settings to enable live export.", "info");
  };

  return (
    <div className="min-h-screen bg-transparent text-white">
      <div className="absolute inset-0 grid-accent opacity-25" aria-hidden />
      <header className="mx-auto flex w-full max-w-6xl items-center justify-between px-6 py-8">
        <div className="flex items-center gap-3">
          <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-cyan-500 text-slate-950 font-bold">
            MM
          </div>
          <div>
            <p className="text-lg font-semibold">MeetMind AI</p>
            <p className="text-xs text-slate-400">Meeting notes &amp; action items</p>
          </div>
        </div>
        <div className="flex items-center gap-3">
          <Link to="/auth" className="text-sm text-slate-300 hover:text-white">
            Login
          </Link>
          <Button asChild>
            <Link to="/dashboard" className="flex items-center gap-2">
              Open dashboard <ArrowRight className="h-4 w-4" />
            </Link>
          </Button>
        </div>
      </header>

      <main className="mx-auto flex w-full max-w-6xl flex-col gap-16 px-6 pb-24">
        <section className="grid gap-10 lg:grid-cols-[1.1fr_0.9fr]">
          <div className="space-y-6" style={{ animation: "fadeUp 0.9s ease" }}>
            <Badge className="bg-cyan-500/15 text-cyan-200 border border-cyan-400/30">
              AI meeting notes • 30h hackathon build
            </Badge>
            <h1 className="text-4xl font-bold leading-tight sm:text-5xl">
              Turn messy meeting notes into crisp summaries &amp; action items.
            </h1>
            <p className="max-w-2xl text-lg text-slate-300">
              MeetMind AI captures decisions, owners, and deadlines from every conversation. Share
              Markdown, export to Trello or Notion, and keep teams accountable.
            </p>
            <div className="flex flex-wrap items-center gap-4">
              <Button asChild size="lg">
                <Link to="/dashboard" className="flex items-center gap-2">
                  Try live demo <Sparkles className="h-4 w-4" />
                </Link>
              </Button>
              <Button asChild variant="outline" size="lg">
                <Link to="/auth">Login / Register</Link>
              </Button>
              <p className="text-sm text-slate-400">Demo comes preloaded with sample transcript.</p>
            </div>
            <div className="flex flex-wrap items-center gap-8 text-sm text-slate-300">
              <div className="flex items-center gap-2">
                <ShieldCheck className="h-4 w-4 text-emerald-400" /> SOC2-ready architecture outline
              </div>
              <div className="flex items-center gap-2">
                <Clock3 className="h-4 w-4 text-cyan-300" /> Summary in under 15 seconds
              </div>
              <div className="flex items-center gap-2">
                <Users className="h-4 w-4 text-violet-300" /> Built for remote teams &amp; founders
              </div>
            </div>
          </div>

          <Card className="relative overflow-hidden border-white/5 bg-white/5 p-6 shadow-2xl">
            <div className="absolute inset-0 bg-gradient-to-br from-cyan-500/10 via-transparent to-violet-500/15" />
            <div className="relative flex flex-col gap-4">
              <div className="flex items-center justify-between">
                <div className="space-y-1">
                  <p className="text-sm text-slate-300">Quick demo</p>
                  <p className="text-xl font-semibold">AI Meeting Digest</p>
                </div>
                <Badge tone="success">Ready</Badge>
              </div>
              <div className="rounded-xl border border-white/5 bg-white/5 p-4">
                <p className="text-xs uppercase tracking-[0.2em] text-cyan-200">Summary</p>
                <p className="mt-2 text-sm text-slate-100">
                  Website revamp launch set for Mar 14. Marketing owns launch plan. Engineering to
                  finalize API stability by Mar 7. Weekly standups move to Tuesdays.
                </p>
              </div>
              <div className="rounded-xl border border-white/5 bg-white/5 p-4">
                <p className="text-xs uppercase tracking-[0.2em] text-cyan-200">Action items</p>
                <ul className="mt-3 space-y-2 text-sm text-slate-100">
                  <li>• Anna to ship homepage copy by Mar 1 (High)</li>
                  <li>• Vic to confirm analytics plan with Data by Feb 27 (Medium)</li>
                  <li>• Priya to update onboarding deck for sales by Mar 5 (High)</li>
                </ul>
              </div>
              <div className="flex flex-wrap gap-3">
                <Button variant="secondary" size="sm" onClick={handleCopyMarkdown}>
                  Copy Markdown
                </Button>
                <Button variant="ghost" size="sm" className="border border-white/10" onClick={handleExportTrello}>
                  Export to Trello
                </Button>
              </div>
            </div>
          </Card>
        </section>

        <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
          {featureBlocks.map((feature) => (
            <Card key={feature.title} className="h-full border-white/5 bg-white/5 p-5">
              <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-cyan-500/15 text-cyan-200">
                {feature.icon}
              </div>
              <h3 className="mt-4 text-lg font-semibold">{feature.title}</h3>
              <p className="mt-2 text-sm text-slate-300">{feature.description}</p>
            </Card>
          ))}
        </section>

        <section className="grid gap-6 lg:grid-cols-[1.2fr_0.8fr]">
          <Card className="border-white/5 bg-white/5 p-6">
            <div className="flex items-center gap-3">
              <Sparkles className="h-5 w-5 text-cyan-300" />
              <p className="text-sm uppercase tracking-[0.25em] text-cyan-200">Built for teams</p>
            </div>
            <h2 className="mt-3 text-2xl font-semibold">Why teams love MeetMind</h2>
            <ul className="mt-4 space-y-3 text-slate-300">
              <li className="flex items-start gap-3">
                <CheckCircle2 className="mt-1 h-4 w-4 text-emerald-300" />
                <span>Export-ready: Markdown, PDF, Trello cards, and Notion pages in one click.</span>
              </li>
              <li className="flex items-start gap-3">
                <CheckCircle2 className="mt-1 h-4 w-4 text-emerald-300" />
                <span>Ownership-first: every task gets an owner, due date, and priority.</span>
              </li>
              <li className="flex items-start gap-3">
                <CheckCircle2 className="mt-1 h-4 w-4 text-emerald-300" />
                <span>Searchable history: find past decisions instantly with filters.</span>
              </li>
            </ul>
            <div className="mt-6 flex flex-wrap gap-3 text-sm text-slate-400">
              <span className="rounded-full bg-white/5 px-3 py-1">Remote teams</span>
              <span className="rounded-full bg-white/5 px-3 py-1">Managers &amp; leads</span>
              <span className="rounded-full bg-white/5 px-3 py-1">Consultants</span>
              <span className="rounded-full bg-white/5 px-3 py-1">Startups</span>
            </div>
          </Card>

          <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-1">
            {pricing.map((plan) => (
              <Card key={plan.name} className="border-white/5 bg-white/5 p-5">
                <div className="flex items-start justify-between">
                  <div>
                    <p className="text-sm text-slate-300">{plan.name}</p>
                    <p className="mt-2 text-3xl font-semibold">{plan.price}</p>
                    <p className="text-xs text-slate-400">{plan.note}</p>
                  </div>
                  <Badge tone="success" className="bg-emerald-500/15 text-emerald-200">
                    Popular
                  </Badge>
                </div>
                <ul className="mt-4 space-y-2 text-sm text-slate-300">
                  {plan.features.map((f) => (
                    <li key={f} className="flex items-start gap-2">
                      <CheckCircle2 className="mt-0.5 h-4 w-4 text-emerald-300" /> {f}
                    </li>
                  ))}
                </ul>
                <Button asChild variant="secondary" className="mt-5 w-full">
                  <Link to="/auth">{plan.cta}</Link>
                </Button>
              </Card>
            ))}
          </div>
        </section>

        <section className="flex flex-col items-center gap-4 text-center">
          <Badge className="bg-white/10 text-white">Demo-first build</Badge>
          <h3 className="text-2xl font-semibold">Ready to see it in action?</h3>
          <p className="max-w-2xl text-slate-300">
            Jump into the dashboard demo with a preloaded transcript, generate AI summary &amp; actions,
            then export to your favorite tools. No setup needed.
          </p>
          <div className="flex flex-wrap items-center justify-center gap-3">
            <Button asChild>
              <Link to="/dashboard" className="flex items-center gap-2">
                Open the dashboard <ArrowRight className="h-4 w-4" />
              </Link>
            </Button>
            <Button asChild variant="outline">
              <Link to="/auth">Create account</Link>
            </Button>
          </div>
        </section>
      </main>
    </div>
  );
}
