"use client";

import { useEffect, useRef, useState } from "react";
import { useNavigate } from "react-router-dom";
import { Bell, Download, Search, Share2, Sparkles, X } from "lucide-react";
import { UserButton } from "@clerk/clerk-react";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { useToast } from "@/lib/toast";

const mockNotifications = [
  { id: 1, text: "Anna completed: Ship homepage copy updates", time: "2m ago", unread: true },
  { id: 2, text: "Victor flagged a risk on analytics events", time: "18m ago", unread: true },
  { id: 3, text: "New meeting summary ready: Launch planning", time: "1h ago", unread: false },
];

const allMeetingsMarkdown = `# All Meeting Summaries – MeetMind AI

## Launch planning — Sprint 12 (Feb 18)
Confirmed Mar 14 launch. Marketing GTM by Feb 29. Engineering freeze Mar 7.

## Customer advisory board (Feb 16)
Enterprise wants SSO + audit logs by Q2. Victor to follow up with Acme.

## Weekly product sync (Feb 15)
Mobile release to April. Priya to update Notion roadmap by EOW.

## Sales enablement workshop (Feb 12)
Sales deck refresh with ROI metrics. Samir to coordinate demo env for AEs.

---
*Generated by MeetMind AI*`;

export function Topbar() {
  const [query, setQuery] = useState("");
  const [showNotifications, setShowNotifications] = useState(false);
  const [notifications, setNotifications] = useState(mockNotifications);
  const notifRef = useRef<HTMLDivElement>(null);
  const navigate = useNavigate();
  const toast = useToast();

  const unreadCount = notifications.filter((n) => n.unread).length;

  // Close notification dropdown when clicking outside
  useEffect(() => {
    const handler = (e: MouseEvent) => {
      if (notifRef.current && !notifRef.current.contains(e.target as Node)) {
        setShowNotifications(false);
      }
    };
    document.addEventListener("mousedown", handler);
    return () => document.removeEventListener("mousedown", handler);
  }, []);

  const handleExportAll = async () => {
    await navigator.clipboard.writeText(allMeetingsMarkdown);
    toast("All meetings copied to clipboard!");
  };

  const handleShare = async () => {
    await navigator.clipboard.writeText(window.location.href);
    toast("Link copied to clipboard!");
  };

  const handleNewSummary = () => {
    navigate("/dashboard");
  };

  const handleSearch = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === "Enter" && query.trim()) {
      navigate(`/history?q=${encodeURIComponent(query.trim())}`);
      setQuery("");
    }
  };

  const markAllRead = () => {
    setNotifications((prev) => prev.map((n) => ({ ...n, unread: false })));
  };

  return (
    <div className="sticky top-0 z-20 flex items-center justify-between gap-4 border-b border-white/5 bg-slate-950/80 px-4 py-4 backdrop-blur-xl">
      <div className="relative flex-1">
        <Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" />
        <Input
          className="pl-10"
          placeholder="Search meetings, owners, tasks... (Enter)"
          value={query}
          onChange={(e) => setQuery(e.target.value)}
          onKeyDown={handleSearch}
        />
      </div>
      <div className="flex items-center gap-2">
        <Button variant="secondary" size="sm" className="hidden sm:inline-flex" onClick={handleExportAll}>
          <Download className="h-4 w-4" /> Export all
        </Button>
        <Button variant="ghost" size="sm" className="text-slate-300" onClick={handleShare}>
          <Share2 className="h-4 w-4" /> Share
        </Button>

        {/* Bell & notifications dropdown */}
        <div className="relative" ref={notifRef}>
          <Button
            variant="ghost"
            size="sm"
            className="relative text-slate-300"
            onClick={() => setShowNotifications((v) => !v)}
          >
            <Bell className="h-4 w-4" />
            {unreadCount > 0 && (
              <span className="absolute -right-0.5 -top-0.5 flex h-4 w-4 items-center justify-center rounded-full bg-cyan-500 text-[10px] font-bold text-slate-950">
                {unreadCount}
              </span>
            )}
          </Button>

          {showNotifications && (
            <div className="absolute right-0 top-full mt-2 w-80 rounded-xl border border-white/10 bg-slate-900 shadow-2xl">
              <div className="flex items-center justify-between border-b border-white/10 px-4 py-3">
                <p className="text-sm font-semibold">Notifications</p>
                <div className="flex items-center gap-2">
                  {unreadCount > 0 && (
                    <button onClick={markAllRead} className="text-xs text-cyan-300 hover:text-cyan-100">
                      Mark all read
                    </button>
                  )}
                  <button onClick={() => setShowNotifications(false)}>
                    <X className="h-4 w-4 text-slate-400 hover:text-white" />
                  </button>
                </div>
              </div>
              <div className="divide-y divide-white/5">
                {notifications.map((n) => (
                  <div key={n.id} className={`flex items-start gap-3 px-4 py-3 ${n.unread ? "bg-white/5" : ""}`}>
                    {n.unread && <span className="mt-1.5 h-2 w-2 flex-shrink-0 rounded-full bg-cyan-400" />}
                    {!n.unread && <span className="mt-1.5 h-2 w-2 flex-shrink-0" />}
                    <div>
                      <p className="text-sm text-slate-100">{n.text}</p>
                      <p className="text-xs text-slate-400">{n.time}</p>
                    </div>
                  </div>
                ))}
              </div>
              <div className="border-t border-white/10 px-4 py-3 text-center">
                <button className="text-xs text-cyan-300 hover:text-cyan-100">View all activity</button>
              </div>
            </div>
          )}
        </div>

        <Button variant="primary" size="sm" className="hidden md:inline-flex" onClick={handleNewSummary}>
          <Sparkles className="h-4 w-4" /> New summary
        </Button>

        <UserButton
          afterSignOutUrl="/auth"
          appearance={{
            variables: { colorPrimary: "#06b6d4" },
            elements: {
              avatarBox: "h-8 w-8 ring-2 ring-cyan-400/40",
            },
          }}
        />
      </div>
    </div>
  );
}
